all: hide unhide

hide: hidev2.c asg1fn.c asg1fn.h
	gcc -o hide hidev2.c asg1fn.c asg2fn.c -Wall
	
unhide: unhidev2.c asg1fn.c asg1fn.h
	gcc -o unhide unhidev2.c asg1fn.c asg2fn.c -Wall

hide-g: hidev2.c asg1fn.c asg1fn.h
	gcc -o hide hidev2.c asg1fn.c asg2fn.c -Wall -g
	
unhide-g: unhidev2.c asg1fn.c asg1fn.h
	gcc -o unhide unhidev2.c asg1fn.c asg2fn.c -Wall -g
